"""add not null to foreign keys

Revision ID: ac072bed52d0
Revises: 8e5c2649e13e
Create Date: 2026-04-03 05:43:13.919146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac072bed52d0'
down_revision: Union[str, Sequence[str], None] = '8e5c2649e13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
